# Generated by Django 4.1.1 on 2022-10-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
