# Generated by Django 4.1.1 on 2022-10-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_technique_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
