# Generated by Django 4.1.1 on 2022-11-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_banner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/banner'),
        ),
    ]
