# Generated by Django 4.1.1 on 2022-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0013_alter_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technique",
            name="age",
        ),
        migrations.AddField(
            model_name="technique",
            name="battery",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Батарейка"
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="count_channel",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Количество каналов"
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="count_programm",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Количество программ прослушивания",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="max_usilenie",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Максимальное акустическое усиление*, (дБ)",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="max_vuzd",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Максимальное акустическое усиление*, (дБ)",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="power_level",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Уровень мощности"
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="type_corpuse",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Тип корпуса"
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="type_signal",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Тип обработки сигнала",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Производитель"
            ),
        ),
    ]
